""" item_names.py """

ITEM_NAMES = [
    'National Chat Masala',
    'Rafhan Strawberry Jelly',
    'Pantene Smooth and Silky Shampoo',
    'L\'Oreal Paris Shampoo',
    'Sunsilk Perfect Straight',
    'Dairy Omung',
    'Lipton Yellow Label (190G)',
    'Head and Shoulders',
    'Vaseline Aloe Fresh Lotion',
    'Shan Achar Gosht',
    'Shan Bombay Biryani',
    'Sunsilk Yellow',
    'Milo 4D',
    'Nestle RED Grapes (200 ml)',
    'Cookania Khaas',
    'Khopra Candy',
    'Bisconni Chocolatto',
    'Cookania Zeerary',
    'Bisconni Cocomo',
    'Heinz Complan Chocolate',
    'Kolson Bravo',
    'Bisconni Chocolate Chip',
    'Nestle Milk Pak',
    'Kernel Popcorn',
    'Peakfreans Party',
    'Laziza Dry Fruit Kheer Mix',
    'LU Gala',
    'Cookania Teatime',
    'Cookania Nutsy',
    'Lotte Choco Pie',
    'Peak Freans Rio (Choco & Vinalla)',
    'Peak Freans Rio (Choco)',
    'JoJo Crunchu Chocolate Bars',
    'LU Bakeri Butter Cookies',
    'Wheatables Biscuits',
    'LU Bakeri Bistiks',
    'LU Tuc',
    'Shakarganj Anytime Apply Juice',
    'Dawn Bread Cupcake Plain',
    'Shezan Mango Drink',
    'Peak Freans Butterpuff Cookies',
    'Shakarganj Anytime Kinnow Juice',
    'National Vanilla Custard',
    'Hilal Ding Dong',
    'Cadbury Perk',
    'Betty Crocker Gluten Free Pizza Crust',
    'Rafhan Strawberry Custard',
    'Nestle Cerelac',
    'National Cornflour',
    'Hico Ice Cream (Praline)',
    'Shan Tez Lal Mirch Powder',
    'Fullo Chocolate and Strawberry',
    'Rafhan Mango Custard',
    'National Jelly',
    'Nestle Chaunsa Juice 200 ml',
    'Mayfair Cremo(Strawberry)',
    'LU Zeera Plus (Half Roll)',
    'LU Candi Original',
    'PeekFreans Sooper',
    'Mayfair Café',
    'Bakers Coco Delight',
    'Rose Petal Ultra Soft Tissues',
    'PreekFreans Marie Biscuits',
    'PreekFreans Butter Puff',
    'Kolson Jam Hearts',
    'Shan Fried Fish Masala',
    'Shan Chiken Tikka Masala',
    'Shan Chicken White Korma Masala',
    'Shan Chaat Masala',
    'Colgate Regular',
    'Qarshi Johar Joshanda',
    'Hilal Baketime',
    'Hilal Cupcake(Strawberry)',
    'Hilal Cupcake(Chocoloate)',
    'Karachi Special Nimko',
    'Shezan All pure Strawberry Nectar',
    'Anytime Fruit Cocktail',
    'Bakers Waltz',
    'Mehran Sindhi Biryani Masala',
    'Olpers 1 litre',
    'Haleeb 1 litre',
    'Crispo Kheer Mix',
    'Mehran Firni Mix',
    'National Biryani Masala',
    'National Qourma',
    'National Achar Gosht',
    'Tiger Biscuit',
    'Al Kabie Red Kidney Beans',
    'National Banana Jelly',
    'National Pistachio Kheer',
    'Oreal Krispy French Fries',
    'Refresh Apple Juice 200ml',
    'Anytime Red Grape 200ml',
    'Prince Chocolate Biscuit',
    'Masoor Washed 1kg',
    'Daal Channa 1kg',
    'Nongshim Noodles',
    'Tang 200g',
    'Shincup Noodles',
    'Milo 200g',
]
